{{- if .Values.replicaSet.enabled }}
{{ $podAnnotations := toYaml .Values.replicaSet.podAnnotations | indent 8 }}
{{ $nodeSelector := toYaml .Values.replicaSet.nodeSelector | indent 8 }}
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: "{{ .Release.Name }}-rs"
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.replicaSet.podAntiaffinity.enabled }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  {{- end }}
  minReadySeconds: {{ default 1 .Values.replicaSet.minReadySeconds}}
  revisionHistoryLimit: {{ .Values.revisionhistory }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
{{ $podAnnotations }}
    spec:
      {{- if .Values.replicaSet.nodeSelector }}
      nodeSelector:
{{ $nodeSelector }}
      {{- end }}
      {{- if .Values.replicaSet.podAntiaffinity.enabled }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - {{ .Release.Name }}
                topologyKey: "kubernetes.io/hostname"
      {{- end }}
      {{- if .Values.replicaSet.serviceAccountName }}
      serviceAccountName: {{ .Values.replicaSet.serviceAccountName }}
      {{- end }}
      {{- if .Values.replicaSet.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.replicaSet.imagePullSecret }}
      {{- end }}
      containers:
      - name: {{ .Release.Name }}
        {{- if .Values.replicaSet.command }}
        command:
          {{- range .Values.replicaSet.command }}
          - {{ . }}
          {{- end }}
        {{- end}}
        {{- if .Values.replicaSet.args }}
        args:
          {{- range .Values.replicaSet.args }}
          - {{ . }}
          {{- end }}
        {{- end}}
        image: "{{ .Values.replicaSet.image.repository }}:{{ .Values.replicaSet.image.tag }}"
        imagePullPolicy: {{ .Values.replicaSet.image.pullPolicy }}
        {{- if .Values.env }}
        env:
{{ toYaml .Values.env | indent 8 }}
        {{- end }}
        {{- if .Values.envFrom }}
        envFrom:
{{ toYaml .Values.envFrom | indent 8 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        {{- if .Values.replicaSet.healthcheck }}
        livenessProbe:
          initialDelaySeconds: {{ default 10 .Values.replicaSet.initialDelaySeconds}}
          periodSeconds: {{ default 10 .Values.replicaSet.periodSeconds}}
          timeoutSeconds: {{ default 1 .Values.replicaSet.timeoutSeconds}}
          successThreshold: 1
          failureThreshold: {{ default 3 .Values.replicaSet.failureThreshold}}
          httpGet:
            path: {{ .Values.replicaSet.healthcheck }}
            port: {{ .Values.service.internalPort }}
        readinessProbe:
          initialDelaySeconds: {{ default 10 .Values.replicaSet.initialDelaySeconds}}
          periodSeconds: {{ default 10 .Values.replicaSet.periodSeconds}}
          timeoutSeconds: {{ default 1 .Values.replicaSet.timeoutSeconds}}
          successThreshold: {{ default 1 .Values.replicaSet.successThreshold}}
          failureThreshold: {{ default 3 .Values.replicaSet.failureThreshold}}
          httpGet:
            path: {{ .Values.replicaSet.healthcheck }}
            port: {{ .Values.service.internalPort }}
        {{- end }}
        {{- if .Values.replicaSet.healthcheckCommand }}
        livenessProbe:
          initialDelaySeconds: {{ default 10 .Values.replicaSet.initialDelaySeconds}}
          periodSeconds: {{ default 10 .Values.replicaSet.periodSeconds}}
          timeoutSeconds: {{ default 1 .Values.replicaSet.timeoutSeconds}}
          successThreshold: 1
          failureThreshold: {{ default 3 .Values.replicaSet.failureThreshold}}
          exec:
            command:
              {{- range .Values.replicaSet.healthcheckCommand }}
              - {{ . }}
              {{- end }}
        readinessProbe:
          initialDelaySeconds: {{ default 10 .Values.replicaSet.initialDelaySeconds}}
          periodSeconds: {{ default 10 .Values.replicaSet.periodSeconds}}
          timeoutSeconds: {{ default 1 .Values.replicaSet.timeoutSeconds}}
          successThreshold: {{ default 1 .Values.replicaSet.successThreshold}}
          failureThreshold: {{ default 3 .Values.replicaSet.failureThreshold}}
          exec:
            command:
              {{- range .Values.replicaSet.healthcheckCommand }}
              - {{ . }}
              {{- end }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- if .Values.replicaSet.extraVolumes }}
      volumes:
{{ toYaml .Values.replicaSet.extraVolumes | indent 6 }}
{{- end }}
{{- end }}