{{- $relname := .Release.Name -}}
{{- $relservice := .Release.Service -}}
{{- $fullname := default .Chart.Name .Values.nameOverride -}}
{{- $chartname := .Chart.Name -}}
{{- $chartversion := .Chart.Version -}}
{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    app: {{ $fullname }} 
    chart: {{ $chartname }}-{{ $chartversion }}
    release: {{ $relname }}
    heritage: {{ $relservice }}
type: {{ .type }}
data:
  {{- range $key, $value := .data }}
    {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end}}
